using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Data;
using System.IO;

public partial class Admin_Zone_TotalList : System.Web.UI.Page
{
	string cmd;
	DBManager dm = new DBManager();
	EncryptionDecryption em = new EncryptionDecryption();
	GenCaptcha gc = new GenCaptcha();
	MyMail mm = new MyMail();
	protected void Page_Load(object sender, EventArgs e)
	{
		string st = "VERIFIED", at = "EQUAL OR ABOVE 75 PERCENT", dep = "B.TECH", br = "AGRICULTURE ENGINEERING", yr = "1st YEAR";
		cmd = "select * from AdminSFS where AdminID='" + Session["aid"] + "'";
		DataTable dt = dm.SelectQuary(cmd);
		if (dt.Rows.Count > 0)
		{
			username.Text = dt.Rows[0][0].ToString();
			dep = "B.TECH";
			br = "AGRICULTURE ENGINEERING";
			yr = "1st YEAR";
			cmd = "select * from SRegistration where Status='" + st + "' and Department='" + dep + "' and Branch='" + br + "' and Year='" + yr + "'";
			DataTable dtbtagreg1 = dm.SelectQuary(cmd);
			btag1reg.Text = " " + dtbtagreg1.Rows.Count.ToString();
			dep = "B.TECH";
			br = "AGRICULTURE ENGINEERING";
			yr = "2nd YEAR";
			cmd = "select * from SRegistration where Status='" + st + "' and Department='" + dep + "' and Branch='" + br + "' and Year='" + yr + "'";
			DataTable dtbtagreg2 = dm.SelectQuary(cmd);
			btag2reg.Text = " " + dtbtagreg2.Rows.Count.ToString();
			dep = "B.TECH";
			br = "AGRICULTURE ENGINEERING";
			yr = "3rd YEAR";
			cmd = "select * from SRegistration where Status='" + st + "' and Department='" + dep + "' and Branch='" + br + "' and Year='" + yr + "'";
			DataTable dtbtagreg3 = dm.SelectQuary(cmd);
			btag3reg.Text = " " + dtbtagreg3.Rows.Count.ToString();
			dep = "B.TECH";
			br = "AGRICULTURE ENGINEERING";
			yr = "4th YEAR";
			cmd = "select * from SRegistration where Status='" + st + "' and Department='" + dep + "' and Branch='" + br + "' and Year='" + yr + "'";
			DataTable dtbtagreg4 = dm.SelectQuary(cmd);
			btag4reg.Text = " " + dtbtagreg4.Rows.Count.ToString();

			dep = "B.TECH";
			br = "CHEMICAL ENGINEERING";
			yr = "1st YEAR";
			cmd = "select * from SRegistration where Status='" + st + "' and Department='" + dep + "' and Branch='" + br + "' and Year='" + yr + "'";
			DataTable dtbtchreg1 = dm.SelectQuary(cmd);
			btch1reg.Text = " " + dtbtchreg1.Rows.Count.ToString();
			dep = "B.TECH";
			br = "CHEMICAL ENGINEERING";
			yr = "2nd YEAR";
			cmd = "select * from SRegistration where Status='" + st + "' and Department='" + dep + "' and Branch='" + br + "' and Year='" + yr + "'";
			DataTable dtbtchreg2 = dm.SelectQuary(cmd);
			btch2reg.Text = " " + dtbtchreg2.Rows.Count.ToString();
			dep = "B.TECH";
			br = "CHEMICAL ENGINEERING";
			yr = "3rd YEAR";
			cmd = "select * from SRegistration where Status='" + st + "' and Department='" + dep + "' and Branch='" + br + "' and Year='" + yr + "'";
			DataTable dtbtchreg3 = dm.SelectQuary(cmd);
			btch3reg.Text = " " + dtbtchreg3.Rows.Count.ToString();
			dep = "B.TECH";
			br = "CHEMICAL ENGINEERING";
			yr = "4th YEAR";
			cmd = "select * from SRegistration where Status='" + st + "' and Department='" + dep + "' and Branch='" + br + "' and Year='" + yr + "'";
			DataTable dtbtchreg4 = dm.SelectQuary(cmd);
			btch4reg.Text = " " + dtbtchreg4.Rows.Count.ToString();

			dep = "B.TECH";
			br = "COMPUTER SCIENCE";
			yr = "1st YEAR";
			cmd = "select * from SRegistration where Status='" + st + "' and Department='" + dep + "' and Branch='" + br + "' and Year='" + yr + "'";
			DataTable dtbtcsreg1 = dm.SelectQuary(cmd);
			btcs1reg.Text = " " + dtbtcsreg1.Rows.Count.ToString();
			dep = "B.TECH";
			br = "COMPUTER SCIENCE";
			yr = "2nd YEAR";
			cmd = "select * from SRegistration where Status='" + st + "' and Department='" + dep + "' and Branch='" + br + "' and Year='" + yr + "'";
			DataTable dtbtcsreg2 = dm.SelectQuary(cmd);
			btcs2reg.Text = " " + dtbtcsreg2.Rows.Count.ToString();
			dep = "B.TECH";
			br = "COMPUTER SCIENCE";
			yr = "3rd YEAR";
			cmd = "select * from SRegistration where Status='" + st + "' and Department='" + dep + "' and Branch='" + br + "' and Year='" + yr + "'";
			DataTable dtbtcsreg3 = dm.SelectQuary(cmd);
			btcs3reg.Text = " " + dtbtcsreg3.Rows.Count.ToString();
			dep = "B.TECH";
			br = "COMPUTER SCIENCE";
			yr = "4th YEAR";
			cmd = "select * from SRegistration where Status='" + st + "' and Department='" + dep + "' and Branch='" + br + "' and Year='" + yr + "'";
			DataTable dtbtcsreg4 = dm.SelectQuary(cmd);
			btcs4reg.Text = " " + dtbtcsreg4.Rows.Count.ToString();

			dep = "B.TECH";
			br = "ELECTRONICS & COMMUNICATION";
			yr = "1st YEAR";
			cmd = "select * from SRegistration where Status='" + st + "' and Department='" + dep + "' and Branch='" + br + "' and Year='" + yr + "'";
			DataTable dtbtecreg1 = dm.SelectQuary(cmd);
			btec1reg.Text = " " + dtbtecreg1.Rows.Count.ToString();
			dep = "B.TECH";
			br = "ELECTRONICS & COMMUNICATION";
			yr = "2nd YEAR";
			cmd = "select * from SRegistration where Status='" + st + "' and Department='" + dep + "' and Branch='" + br + "' and Year='" + yr + "'";
			DataTable dtbtecreg2 = dm.SelectQuary(cmd);
			btec2reg.Text = " " + dtbtecreg2.Rows.Count.ToString();
			dep = "B.TECH";
			br = "ELECTRONICS & COMMUNICATION";
			yr = "3rd YEAR";
			cmd = "select * from SRegistration where Status='" + st + "' and Department='" + dep + "' and Branch='" + br + "' and Year='" + yr + "'";
			DataTable dtbtecreg3 = dm.SelectQuary(cmd);
			btec3reg.Text = " " + dtbtecreg3.Rows.Count.ToString();
			dep = "B.TECH";
			br = "ELECTRONICS & COMMUNICATION";
			yr = "4th YEAR";
			cmd = "select * from SRegistration where Status='" + st + "' and Department='" + dep + "' and Branch='" + br + "' and Year='" + yr + "'";
			DataTable dtbtecreg4 = dm.SelectQuary(cmd);
			btec4reg.Text = " " + dtbtecreg4.Rows.Count.ToString();

			dep = "B.TECH";
			br = "ELECTRONICS & INSTRUMENTATION";
			yr = "1st YEAR";
			cmd = "select * from SRegistration where Status='" + st + "' and Department='" + dep + "' and Branch='" + br + "' and Year='" + yr + "'";
			DataTable dtbteireg1 = dm.SelectQuary(cmd);
			btei1reg.Text = " " + dtbteireg1.Rows.Count.ToString();
			dep = "B.TECH";
			br = "ELECTRONICS & INSTRUMENTATION";
			yr = "2nd YEAR";
			cmd = "select * from SRegistration where Status='" + st + "' and Department='" + dep + "' and Branch='" + br + "' and Year='" + yr + "'";
			DataTable dtbteireg2 = dm.SelectQuary(cmd);
			btei2reg.Text = " " + dtbteireg2.Rows.Count.ToString();
			dep = "B.TECH";
			br = "ELECTRONICS & INSTRUMENTATION";
			yr = "3rd YEAR";
			cmd = "select * from SRegistration where Status='" + st + "' and Department='" + dep + "' and Branch='" + br + "' and Year='" + yr + "'";
			DataTable dtbteireg3 = dm.SelectQuary(cmd);
			btei3reg.Text = " " + dtbteireg3.Rows.Count.ToString();
			dep = "B.TECH";
			br = "ELECTRONICS & INSTRUMENTATION";
			yr = "4th YEAR";
			cmd = "select * from SRegistration where Status='" + st + "' and Department='" + dep + "' and Branch='" + br + "' and Year='" + yr + "'";
			DataTable dtbteireg4 = dm.SelectQuary(cmd);
			btei4reg.Text = " " + dtbteireg4.Rows.Count.ToString();

			dep = "B.TECH";
			br = "MECHANICAL ENGINEERING";
			yr = "1st YEAR";
			cmd = "select * from SRegistration where Status='" + st + "' and Department='" + dep + "' and Branch='" + br + "' and Year='" + yr + "'";
			DataTable dtbtmereg1 = dm.SelectQuary(cmd);
			btme1reg.Text = " " + dtbtmereg1.Rows.Count.ToString();
			dep = "B.TECH";
			br = "MECHANICAL ENGINEERING";
			yr = "2nd YEAR";
			cmd = "select * from SRegistration where Status='" + st + "' and Department='" + dep + "' and Branch='" + br + "' and Year='" + yr + "'";
			DataTable dtbtmereg2 = dm.SelectQuary(cmd);
			btme2reg.Text = " " + dtbtmereg2.Rows.Count.ToString();
			dep = "B.TECH";
			br = "MECHANICAL ENGINEERING";
			yr = "3rd YEAR";
			cmd = "select * from SRegistration where Status='" + st + "' and Department='" + dep + "' and Branch='" + br + "' and Year='" + yr + "'";
			DataTable dtbtmereg3 = dm.SelectQuary(cmd);
			btme3reg.Text = " " + dtbtmereg3.Rows.Count.ToString();
			dep = "B.TECH";
			br = "MECHANICAL ENGINEERING";
			yr = "4th YEAR";
			cmd = "select * from SRegistration where Status='" + st + "' and Department='" + dep + "' and Branch='" + br + "' and Year='" + yr + "'";
			DataTable dtbtmereg4 = dm.SelectQuary(cmd);
			btme4reg.Text = " " + dtbtmereg4.Rows.Count.ToString();

			dep = "B.TECH";
			br = "INFORMATION TECHNOLOGY";
			yr = "1st YEAR";
			cmd = "select * from SRegistration where Status='" + st + "' and Department='" + dep + "' and Branch='" + br + "' and Year='" + yr + "'";
			DataTable dtbtitreg1 = dm.SelectQuary(cmd);
			btit1reg.Text = " " + dtbtitreg1.Rows.Count.ToString();
			dep = "B.TECH";
			br = "INFORMATION TECHNOLOGY";
			yr = "2nd YEAR";
			cmd = "select * from SRegistration where Status='" + st + "' and Department='" + dep + "' and Branch='" + br + "' and Year='" + yr + "'";
			DataTable dtbtitreg2 = dm.SelectQuary(cmd);
			btit2reg.Text = " " + dtbtitreg2.Rows.Count.ToString();
			dep = "B.TECH";
			br = "INFORMATION TECHNOLOGY";
			yr = "3rd YEAR";
			cmd = "select * from SRegistration where Status='" + st + "' and Department='" + dep + "' and Branch='" + br + "' and Year='" + yr + "'";
			DataTable dtbtitreg3 = dm.SelectQuary(cmd);
			btit3reg.Text = " " + dtbtitreg3.Rows.Count.ToString();
			dep = "B.TECH";
			br = "INFORMATION TECHNOLOGY";
			yr = "4th YEAR";
			cmd = "select * from SRegistration where Status='" + st + "' and Department='" + dep + "' and Branch='" + br + "' and Year='" + yr + "'";
			DataTable dtbtitreg4 = dm.SelectQuary(cmd);
			btit4reg.Text = " " + dtbtitreg4.Rows.Count.ToString();

			dep = "MBA";
			br = "MBA";
			yr = "1st YEAR";
			cmd = "select * from SRegistration where Status='" + st + "' and Department='" + dep + "' and Branch='" + br + "' and Year='" + yr + "'";
			DataTable dtmbreg1 = dm.SelectQuary(cmd);
			mb1reg.Text = " " + dtmbreg1.Rows.Count.ToString();
			dep = "MBA";
			br = "MBA";
			yr = "2nd YEAR";
			cmd = "select * from SRegistration where Status='" + st + "' and Department='" + dep + "' and Branch='" + br + "' and Year='" + yr + "'";
			DataTable dtmbreg2 = dm.SelectQuary(cmd);
			mb2reg.Text = " " + dtmbreg2.Rows.Count.ToString();

			dep = "MBA";
			br = "MBA (HA)";
			yr = "1st YEAR";
			cmd = "select * from SRegistration where Status='" + st + "' and Department='" + dep + "' and Branch='" + br + "' and Year='" + yr + "'";
			DataTable dtmbhareg1 = dm.SelectQuary(cmd);
			mbha1reg.Text = " " + dtmbhareg1.Rows.Count.ToString();
			dep = "MBA";
			br = "MBA (HA)";
			yr = "2nd YEAR";
			cmd = "select * from SRegistration where Status='" + st + "' and Department='" + dep + "' and Branch='" + br + "' and Year='" + yr + "'";
			DataTable dtmbhareg2 = dm.SelectQuary(cmd);
			mbha2reg.Text = " " + dtmbhareg2.Rows.Count.ToString();

			dep = "MCA";
			br = "NO BRANCH";
			yr = "1st YEAR";
			cmd = "select * from SRegistration where Status='" + st + "' and Department='" + dep + "' and Branch='" + br + "' and Year='" + yr + "'";
			DataTable dtmcreg1 = dm.SelectQuary(cmd);
			mc1reg.Text = " " + dtmcreg1.Rows.Count.ToString();
			dep = "MCA";
			br = "NO BRANCH";
			yr = "2nd YEAR";
			cmd = "select * from SRegistration where Status='" + st + "' and Department='" + dep + "' and Branch='" + br + "' and Year='" + yr + "'";
			DataTable dtmcreg2 = dm.SelectQuary(cmd);
			mc2reg.Text = " " + dtmcreg2.Rows.Count.ToString();


			cmd = "select * from FeedbackCnI";
			DataTable dttotci = dm.SelectQuary(cmd);
			totfci.Text = dttotci.Rows.Count.ToString();
			st = "VERIFIED";
			cmd = "select * from FeedbackCnI where Status='" + st + "'";
			DataTable dtverci = dm.SelectQuary(cmd);
			verfci.Text = dtverci.Rows.Count.ToString();
			st = "NOT VERIFIED";
			cmd = "select * from FeedbackCnI where Status='" + st + "'";
			DataTable dtnverci = dm.SelectQuary(cmd);
			nverfci.Text = dtnverci.Rows.Count.ToString();
			st = "REJECTED";
			cmd = "select * from FeedbackCnI where Status='" + st + "'";
			DataTable dtrejci = dm.SelectQuary(cmd);
			rejfci.Text = dtrejci.Rows.Count.ToString();

			cmd = "select * from FeedbackTnC";
			DataTable dttottc = dm.SelectQuary(cmd);
			totftc.Text = dttottc.Rows.Count.ToString();
			at = "EQUAL OR ABOVE 75 PERCENT";
			st = "VERIFIED";
			cmd = "select * from FeedbackTnC where Attandance='" + at + "'";
			DataTable dtverfaetc = dm.SelectQuary(cmd);
			verfaeftc.Text = dtverfaetc.Rows.Count.ToString();
			at = "BELOW 75 PERCENT";
			st = "VERIFIED";
			cmd = "select * from FeedbackTnC where Attandance='" + at + "'";
			DataTable dtverfbtc = dm.SelectQuary(cmd);
			verfbftc.Text = dtverfbtc.Rows.Count.ToString();
			at = "BELOW 75 PERCENT";
			st = "NOT VERIFIED";
			cmd = "select * from FeedbackTnC where Status='" + st + "'";
			DataTable dtnverftc = dm.SelectQuary(cmd);
			nverftc.Text = dtnverftc.Rows.Count.ToString();
			st = "REJECTED";
			cmd = "select * from FeedbackTnC where Status='" + st + "'";
			DataTable dtrejftc = dm.SelectQuary(cmd);
			rejftc.Text = dtrejftc.Rows.Count.ToString();

		}
		else
		{
			Response.Redirect("Home");
		}
	}
}